" .vimrc

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" KeyMap
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set mapleader
let mapleader = ","
let g:mapleader = ","
nnoremap ; :
nnoremap <leader>' '
nnoremap ' "

map <F5> :NERDTreeMirrorOpen<CR>
map <F5> :NERDTreeToggle<CR>
map <F6> :TagbarToggle<CR>
map <F8> :IndentLinesToggle<CR>
map <F9> :noh<CR>

" 窗口跳转
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" use Ctrl+[l|n|p|c] to list|next|previous|jump to count the result
map <C-x>l <ESC>:cl<CR>
map <C-x>n <ESC>:cn<CR>
map <C-x>p <ESC>:cp<CR>
map <C-x>c <ESC>:cc<CR>

" Fast saving
nmap <silent> <leader>ww :w<cr>
nmap <silent> <leader>wf :w!<cr>

" Fast redraw   重绘屏幕
nmap <silent> <leader>rr :redraw!<cr>

" Tab操作快捷方式!
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>td :tabnew<cr>
map <leader>te :tabedit<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove<cr>
try
  set switchbuf=useopen
  set stal=1
catch
endtry

" 错误跳转
map <leader>lp :lprevious<cr>
map <leader>ll :lnext<cr>


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Environment
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set helplang=cn
let helptags=$VIMFILES.'/doc'
let $VIMFILES=$HOME.'/.vim'
let $VIMRCFILES=$HOME.'/.vimrc'

autocmd bufwritepost .vimrc source $VIMRCFILES

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
source $VIMRUNTIME/vimrc_example.vim

set mouse-=a

set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,ucs-bom,cp936,gb18030,gbk2312,gbk,big5,euc-jp,euc-kr,latin1
let $LANG='zh_CN.UTF-8'
set langmenu=zh_CN
set imcmdline

if has("win32")
    set termencoding=chinese
    " source $VIMRUNTIME/mswin.vim
    behave mswin
    language message zh_CN.UTF-8
endif

if has("gui_running")
    set guioptions-=m
    set guioptions-=T
    set guioptions-=L
    set guioptions-=r
    set guioptions-=b
    set showtabline=0
    set background=light
    set lines=40 columns=160 	  " 指定窗口大小，lines为高度，columns为宽度
    " au GUIEnter * simalt ~x 	" 窗口启动时自动最大化
    " winpos 60 60            	" 指定窗口出现的位置，坐标原点在屏幕左上角
endif

" viminfo stores the the state of your previous editing session
set viminfo+=n~/.vim/viminfo

" Save your backups to a less annoying place than the current directory.
if isdirectory($HOME . '/.vim/~backup') == 0
  :silent !mkdir -p ~/.vim/~backup >/dev/null 2>&1
endif
set backupdir-=.
set backupdir-=~/
set backupdir^=~/.vim/~backup/
set backup

" Save your swp files to a less annoying place than the current directory.
if isdirectory($HOME . '/.vim/swap') == 0
  :silent !mkdir -p ~/.vim/swap >/dev/null 2>&1
endif
set directory=~/.vim/swap//
set directory+=.

" undofile - This allows you to use undos after exiting and restarting
" :help undo-persistence
if exists("+undofile")
  if isdirectory($HOME . '/.vim/~undo') == 0
    :silent !mkdir -p ~/.vim/~undo > /dev/null 2>&1
  endif
  set undodir=~/.vim/~undo//
  set undofile
  set undolevels=1000
endif

" Setting Configuration

syntax on                           " 语法高亮
set nocompatible                    " 关闭 vi 兼容模式
set number                          " 显示行号
set cursorline                      " 突出显示当前行
set cursorcolumn                    " 突出显示当前列
set ruler                           " 打开状态栏标尺
set et                              " 键入tab时使用空格
set background=dark
set guifont=Consolas:h12:cANSI

set t_Co=256                        " 终端颜色数量
set t_vb=                           " 终端置空错误铃声

set autochdir                       " 自动切换当前目录为当前文件所在的目录
set nobackup                        " 覆盖文件时不备份
set backupcopy=yes                  " 设置备份时的行为为覆盖

set ignorecase smartcase            " 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set nowrapscan                      " 禁止在搜索到文件两端时重新搜索
set incsearch                       " 输入搜索内容时就显示搜索结果
set hlsearch                        " 搜索时高亮显示被找到的文本

set noerrorbells                    " 关闭错误信息响铃
set novisualbell                    " 关闭使用可视响铃代替呼叫

set showmatch                       " 插入括号时，短暂地跳转到匹配的对应括号
set matchtime=2                     " 短暂跳转到匹配括号的时间，显示配对括号的十分之一秒数

set hidden                          " 允许在有未保存的修改时切换缓冲区，此时的修改由 vim 负责保存
set autoread                        " 自动重新读取当文件在外部被修改的时候
set autowrite                       " 自动保存文件在适当的时候

set autoindent                      " 开启新行时(o|O)，自动缩进
set cindent                         " C语言自动缩进
set smartindent                     " 开启新行时使用智能自动缩进

set backspace=indent,eol,start      " 不设定在插入状态无法用退格键和 Delete 键删除回车符

set pastetoggle=<F11>               " 不缩进粘贴 激活/取消 paste模式

set foldenable                      " 允许代码折叠
set foldmethod=syntax               " 根据代码缩进折叠
set foldlevel=100                   " 不要自动缩进（但可以手动缩进）
set foldopen-=search                " 搜索时，不需要打开已被折叠的代码
set foldopen-=undo                  " 运行“撤销”命令的时不要打开折叠
set foldcolumn=0                    " 设置折叠区域的宽度
set foldclose=all                   " 设置为自动关闭折叠

set shiftwidth=4                    " 设定 << 和 >> 命令移动时的宽度为 4
set softtabstop=4                   " 使得按退格键时可以一次删掉 4 个空格
set tabstop=4                       " 设定 tab 长度为 4
set laststatus=2                    " 显示状态栏 (默认值为 1, 无法显示状态栏)
set cmdheight=1                     " 设定命令行的行数为 1

set history=1000                    " :命令历史和/?搜索模式历史记录，vim默认20
set scrolloff=10                    " 光标上下两侧保留的最小屏幕数
set report=0                        " 报告改变行数的阈值
set wildmenu                        " 打开时，命令行以增强模式补全
set whichwrap+=<,>,[,]              " 行首和行为跳到上一行行为或下一行行首
set diffopt=filler,context:4        " diff模式的设置

set list
set listchars=tab:\ \ ,trail:\ ,extends:>,precedes:<,eol:\ 

set shortmess=atI

set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\ %c:%l/%L%)\

" tags files CTRL-] uses
set tags+=$VIMRUNTIME/doc/tags
set tags+=$VIMFILES/doc/tags
set tags+=~/.vim/tags/systags
set tags+=~/.vim/tags/cpptags
set tags+=../tags
set tags+=./tags

" ctags -I __THROW --file-scope=yes --langmap=c:+.h --languages=c,c++
" --links=yes --c-kinds=+p -R -f ~/.vim/tags/systags /usr/include /usr/local/include

" ctags -R --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ /sorcepath
"TAGFILES = "libstdc++.tag = http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen"
map <F2> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

autocmd BufRead,BufNewFile  *.ejs   set filetype=html
autocmd FileType javascript         set ts=2 sts=2 sw=2 et
autocmd FileType javascript         set textwidth=80 colorcolumn=+1


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugin Configuration
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let autoInstallVundle=1
let has_vundle=1
if autoInstallVundle == 1 && !filereadable($HOME."/.vim/bundle/Vundle.vim/README.md")
    echo "Installing Vundle..."
    echo ""
    silent !mkdir -p $HOME/.vim/bundle
    silent !git clone https://github.com/gmarik/Vundle.vim $HOME/.vim/bundle/Vundle.vim
    let has_vundle=0
endif

filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" usage: :PluginInstall OR vim +PluginInstall +qall
Plugin 'gmarik/Vundle.vim'

" EditorConfig plugin for Vim
Plugin 'editorconfig/editorconfig-vim'

" A tree explorer plugin for vim.
Plugin 'scrooloose/nerdtree'
let NERDTreeMinimalUI=1
let NERDTreeQuitOnOpen=0
let NERDTreeDirArrows=1
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=0

" How can I change default arrows?
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" How can I open a NERDTree automatically when vim starts up if no files were specified?
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" How can I close vim if the only window left open is a NERDTree?
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Extra syntax and highlight for nerdtree files
Plugin 'tiagofumo/vim-nerdtree-syntax-highlight'

" NERDTree and tabs together in Vim, painlessly
Plugin 'jistr/vim-nerdtree-tabs'

" A plugin of NERDTree showing git status
Plugin 'Xuyuanp/nerdtree-git-plugin'

" Tagbar: a class outline viewer for Vim. better then taglist.
Plugin 'majutsushi/tagbar'
let g:tagbar_iconchars = ['▸', '▾']
" let g:tagbar_ctags_bin
" autocmd VimEnter * nested :TagbarOpen

" Elegant buffer explorer - takes very little screen space
Plugin 'fholgado/minibufexpl.vim'

" Powerline is a statusline plugin for vim
Plugin 'powerline/powerline',{'rtp': 'powerline/bindings/vim/'}

" The fancy start screen for Vim.
Plugin 'mhinz/vim-startify'
nnoremap <leader>st  :Startify<cr>

" Most Recently Used (MRU) Vim Plugin
Plugin 'vim-scripts/mru.vim'
map <leader>m :MRU<cr>
let MRU_Max_Menu_Entries = 20
let MRU_Max_Submenu_Entries = 20
let MRU_Window_Height = 15

" This vim plugin allows toggling bookmarks per line.
" nmap <Leader><Leader> <Plug>BookmarkToggle
" nmap <Leader>i <Plug>BookmarkAnnotate
" nmap <Leader>a <Plug>BookmarkShowAll
" nmap <Leader>j <Plug>BookmarkNext
" nmap <Leader>k <Plug>BookmarkPrev
" nmap <Leader>c <Plug>BookmarkClear
" nmap <Leader>x <Plug>BookmarkClearAll
" nmap <Leader>kk <Plug>BookmarkMoveUp
" nmap <Leader>jj <Plug>BookmarkMoveDown
Plugin 'MattesGroeger/vim-bookmarks'
highlight BookmarkSign ctermbg=NONE ctermfg=160
highlight BookmarkLine ctermbg=194 ctermfg=NONE
let g:bookmark_sign = '♥'
let g:bookmark_highlight_lines = 1

" Eclipse like task list :TaskList
Plugin 'vim-scripts/TaskList.vim'

" Better Rainbow Parentheses
Plugin 'kien/rainbow_parentheses.vim'

" Vim plugin, provides insert mode auto-completion for quotes, parens, brackets, etc.
Plugin 'Raimondi/delimitMate'

" surround.vim: quoting/parenthesizing made simple
Plugin 'tpope/vim-surround'

" repeat.vim: enable repeating supported plugin maps with '.'
Plugin 'tpope/vim-repeat'

" True Sublime Text style multiple selections for Vim
Plugin 'terryma/vim-multiple-cursors'

" A Vim alignment plugin
Plugin 'junegunn/vim-easy-align'

" UltiSnips - The ultimate snippet solution for Vim. Send pull requests to SirVer/ultisnips!
Plugin 'SirVer/ultisnips'

" snipMate.vim aims to be a concise vim script that implements some of TextMate's snippets features in Vim. 
Plugin 'msanders/snipmate.vim'

" A vim plugin to display the indention levels with thin vertical lines
Plugin 'Yggdroot/indentLine'
let g:indentLine_color_term = 239
let g:indentLine_color_gui = '#A4E57E'
let g:indentLine_color_tty_light = 7
let g:indentLine_color_dark = 1
let g:indentLine_concealcursor = 'vc'
let g:indentLine_conceallevel = 2
let g:indentLine_char = '¦'
let g:indentLine_enabled = 1

" Highlights trailing whitespace in red and provides :FixWhitespace to fix it.
Plugin 'bronson/vim-trailing-whitespace'

" Fuzzy file, buffer, mru, tag, etc finder.
Plugin 'ctrlpvim/ctrlp.vim'
map <c-p> :CtrlP<CR>
let g:ctrlp_working_path_mode = 'ra'
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.tar.gz     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.tar.gz,*.exe  " Windows
set wildignore+=*/node_modules/*
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

" A simple function navigator for ctrlp.vim
Plugin 'tacahiroy/ctrlp-funky'

" Fast and Easy Find and Replace Across Multiple Files
" <Leader>vv  - Grep for the word under the cursor, match all occurences,
Plugin 'dkprice/vim-easygrep'
let g:EasyGrepMode = 2
let g:EasyGrepCommand = 0                   " Use vimgrep:0, grepprg:1
let g:EasyGrepRecursive  = 1                " Recursive searching
let g:EasyGrepIgnoreCase = 1                " not ignorecase:0
let g:EasyGrepFilesToExclude = "*.bak, *~, cscope.*, *.a, *.o, *.pyc"

" Helps you win at grep.
Plugin 'mhinz/vim-grepper'

" An ack.vim alternative mimics Ctrl-Shift-F on Sublime Text 2
" :CtrlSF [pattern]
Plugin 'dyng/ctrlsf.vim'

" Vim plugin for the Perl module / CLI script 'ack'
" sudo apt install ack-grep
Plugin 'mileszs/ack.vim'

" Unite and create user interfaces
Plugin 'Shougo/unite.vim'

" Vim motions on speed!
" Type <Leader><Leader>w(<Plug>(easymotion-w)) to trigger the word motion w
" Type <Leader><Leader>fo, and all "o" characters are highlighted
Plugin 'Lokaltog/vim-easymotion'
" <Leader>f{char} to move to {char}
map  <Leader>f <Plug>(easymotion-bd-f)
nmap <Leader>f <Plug>(easymotion-overwin-f)

" s{char}{char} to move to {char}{char}
nmap s <Plug>(easymotion-overwin-f2)

" Move to line
map <Leader>L <Plug>(easymotion-bd-jk)
nmap <Leader>L <Plug>(easymotion-overwin-line)

" Move to word
map  <Leader>w <Plug>(easymotion-bd-w)
nmap <Leader>w <Plug>(easymotion-overwin-w)

" The missing motion for Vim
" Sneak is invoked with s followed by exactly two characters: s{char}{char}
Plugin 'justinmk/vim-sneak'

" Vim script for text filtering and alignment
Plugin 'godlygeek/tabular'

" Show a diff via Vim sign column.
" NOTE: If git is the only version control system you use, I suggest having a look at vim-gitgutter.
" Plugin 'mhinz/vim-signify'

" A Vim plugin which shows a git diff in the gutter (sign column) and stages/reverts hunks.
Plugin 'airblade/vim-gitgutter'

" A solid language pack for Vim.
Plugin 'sheerun/vim-polyglot'

" Node.js plugins
Plugin 'moll/vim-node'

" Beautifier for javascript
Plugin 'einars/js-beautify'

" Vim plugins for HTML and CSS hi-speedcoding. emmet for vim
Plugin 'mattn/emmet-vim'

" css/less/sass/html color preview for vim
Plugin 'gko/vim-coloresque'

" Syntax Highligth for Vue.js components
Plugin 'posva/vim-vue'

" Syntax checking hacks for vim
Plugin 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']

" Vim plugin for intensely orgasmic commenting
Plugin 'scrooloose/nerdcommenter'
" [count]<leader>cc |NERDComComment|              " Comment out the current line or text selected in visual mode.
" [count]<leader>cn |NERDComNestedComment|        " Same as <leader>cc but forces nesting.
" [count]<leader>c<space> |NERDComToggleComment|  " Toggles the comment state of the selected line(s).
" [count]<leader>cm |NERDComMinimalComment|       " Comments the given lines using only one set of multipart delimiters.
" [count]<leader>ci |NERDComInvertComment|        " Toggles the comment state of the selected line(s) individually.
" [count]<leader>cs |NERDComSexyComment|          " Comments out the selected lines ``sexily''
" [count]<leader>cy |NERDComYankComment|          " Same as <leader>cc except that the commented line(s) are yanked first.
" <leader>c$ |NERDComEOLComment|                  " Comments the current line from the cursor to the end of line.
" <leader>cA |NERDComAppendComment|               " Adds comment delimiters to the end of line and goes into insert mode between them.
" |NERDComInsertComment|                          " Adds comment delimiters at the current cursor position and inserts between. Disabled by default.
" <leader>ca |NERDComAltDelim|                    " Switches to the alternative set of delimiters.
" [count]<leader>cl
" [count]<leader>cb |NERDComAlignedComment|       " Same as |NERDComComment| except that the delimiters are aligned down the left side (<leader>cl) or both sides (<leader>cb).
" [count]<leader>cu |NERDComUncommentLine|        " Uncomments the selected line(s).

" A code-completion engine for Vim
" Plugin 'Valloric/YouCompleteMe'
" let g:ycm_global_ycm_extra_conf='~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
" let g:ycm_collect_identifiers_from_tags_files = 1
" let g:ycm_seed_identifiers_with_syntax = 1
" let g:ycm_confirm_extra_conf = 0

" Theme plugin
" Plugin 'morhetz/gruvbox'
" Plugin 'chriskempson/vim-tomorrow-theme'
" Plugin 'altercation/vim-colors-solarized'
" Plugin 'goatslacker/mango.vim'
Plugin 'tomasr/molokai'

call vundle#end()
filetype plugin indent on

if autoInstallVundle == 1 && has_vundle == 0
    :silent! PluginInstall
    :qa
endif

" color gruvbox
" colorscheme default         " 设定配色方案
" colorscheme desert
" colorscheme Tomorrow-Night-Eighties
" colorscheme solarized
colorscheme molokai
let g:solarized_termcolors=256
